/*
 * JS for Heritage_north20 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c35a8c9-8dd3-4ac5-b1cb-67446d582dfb';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "SafewalkAlerts",
    "location": "SafewalkAlerts.html"
}, {
    "name": "MCampus",
    "location": "MCampus.html"
}, {
    "name": "MParkingLots",
    "location": "MParkingLots.html"
}, {
    "name": "FindClass",
    "location": "FindClass.html"
}, {
    "name": "Services",
    "location": "Services.html"
}, {
    "name": "ParkadeMapsLocations",
    "location": "ParkadeMapsLocations.html"
}, {
    "name": "Newsfeed",
    "location": "Newsfeed.html"
}, {
    "name": "MBusStop",
    "location": "MBusStop.html"
}, {
    "name": "PublicTransit",
    "location": "PublicTransit.html"
}, {
    "name": "MToujours",
    "location": "MToujours.html"
}, {
    "name": "Emergency",
    "location": "Emergency.html"
}, {
    "name": "MStudyAreas",
    "location": "MStudyAreas.html"
}, {
    "name": "BusSelection",
    "location": "BusSelection.html"
}, {
    "name": "MWashrooms",
    "location": "MWashrooms.html"
}, {
    "name": "MAED",
    "location": "MAED.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "MComp",
    "location": "MComp.html"
}, {
    "name": "BugReport",
    "location": "BugReport.html"
}, {
    "name": "MExits",
    "location": "MExits.html"
}, {
    "name": "MFE",
    "location": "MFE.html"
}, {
    "name": "ClassroomAvailability",
    "location": "ClassroomAvailability.html"
}, {
    "name": "Parkade",
    "location": "Parkade.html"
}, {
    "name": "MenuToujours",
    "location": "MenuToujours.html"
}, {
    "name": "Heritage_south20",
    "location": "Heritage_south20.html"
}, {
    "name": "Heritage_north20",
    "location": "Heritage_north20.html"
}, {
    "name": "SuccessfulSubmission",
    "location": "SuccessfulSubmission.html"
}, {
    "name": "Food",
    "location": "Food.html"
}];

function Heritage_north20_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_21': 'Heritage_north20_mobilebutton_21',
        'mobilecarousel_52': 'Heritage_north20_mobilecarousel_52',
        'mobilecarouselitem_53': 'Heritage_north20_mobilecarouselitem_53',
        'mobilelabel_56': 'Heritage_north20_mobilelabel_56',
        'morning_grid': 'Heritage_north20_morning_grid',
        'mobilegridcell_60': 'Heritage_north20_mobilegridcell_60',
        'morning_lable': 'Heritage_north20_morning_lable',
        'mobilecarouselitem_54': 'Heritage_north20_mobilecarouselitem_54',
        'mobilelabel_57': 'Heritage_north20_mobilelabel_57',
        'afternoon_grid': 'Heritage_north20_afternoon_grid',
        'mobilegridcell_65': 'Heritage_north20_mobilegridcell_65',
        'afternoon_label': 'Heritage_north20_afternoon_label',
        'mobilecarouselitem_55': 'Heritage_north20_mobilecarouselitem_55',
        'mobilelabel_58': 'Heritage_north20_mobilelabel_58',
        'evening_grid': 'Heritage_north20_evening_grid',
        'mobilegridcell_70': 'Heritage_north20_mobilegridcell_70',
        'evening_lable': 'Heritage_north20_evening_lable',
        'mobilenavbar_22': 'Heritage_north20_mobilenavbar_22',
        'mobilenavbaritem_23': 'Heritage_north20_mobilenavbaritem_23'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Heritage_north20_afternoon_shedule_onbeforesend_mapping_0"] = {
        "homeScreen": "Heritage_north20",
        "directions": [

        {

            "to_name": "afternoon_shedule",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["Heritage_north20_afternoon_shedule_onsuccess_mapping_0"] = {
        "homeScreen": "Heritage_north20",
        "directions": [

        {
            "from_name": "afternoon_shedule",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Heritage_north20",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['afternoon_grid']"

            },

            {

                "source": "$['body'][i]['time']",
                "target": "$['afternoon_grid']['afternoon_label:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Heritage_north20_evening_schedule_onbeforesend_mapping_0"] = {
        "homeScreen": "Heritage_north20",
        "directions": [

        {

            "to_name": "evening_schedule",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["Heritage_north20_evening_schedule_onsuccess_mapping_0"] = {
        "homeScreen": "Heritage_north20",
        "directions": [

        {
            "from_name": "evening_schedule",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Heritage_north20",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['evening_grid']"

            },

            {

                "source": "$['body'][i]['time']",
                "target": "$['evening_grid']['evening_lable:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Heritage_north20_morning_schedule_onbeforesend_mapping_0"] = {
        "homeScreen": "Heritage_north20",
        "directions": [

        {

            "to_name": "morning_schedule",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["Heritage_north20_morning_schedule_onsuccess_mapping_0"] = {
        "homeScreen": "Heritage_north20",
        "directions": [

        {
            "from_name": "morning_schedule",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Heritage_north20",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['morning_grid']"

            },

            {

                "source": "$['body'][i]['time']",
                "target": "$['morning_grid']['morning_lable:text']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.afternoon_shedule = Apperyio.datasources.afternoon_shedule = new Apperyio.DataSource(Heritage_Northmount_20_afternoon_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Heritage_north20_afternoon_shedule_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Heritage_north20");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Heritage_north20_afternoon_shedule_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.evening_schedule = Apperyio.datasources.evening_schedule = new Apperyio.DataSource(Heritage_Northmount_20_evening_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Heritage_north20_evening_schedule_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Heritage_north20");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Heritage_north20_evening_schedule_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.morning_schedule = Apperyio.datasources.morning_schedule = new Apperyio.DataSource(Heritage_Northmount_20_morning_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Heritage_north20_morning_schedule_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Heritage_north20");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Heritage_north20_morning_schedule_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Heritage_north20';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Heritage_north20_onLoad = function() {
            Heritage_north20_elementsExtraJS();

            try {
                morning_schedule.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            try {
                afternoon_shedule.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            try {
                evening_schedule.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            Heritage_north20_deviceEvents();
            Heritage_north20_windowEvents();
            Heritage_north20_elementsEvents();
        };

    // screen window events


    function Heritage_north20_windowEvents() {

        $('#Heritage_north20').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Heritage_north20_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Heritage_north20_elementsExtraJS() {
        // screen (Heritage_north20) extra code

        /* mobilecarousel_52*/
        var mobilecarousel_52_options = {
            indicatorsListClass: "ui-carousel-indicators",
            showIndicator: true,
            showTitle: true,
            titleBuildIn: false,
            titleIsText: true,
            animationDuration: 250,
            useLegacyAnimation: false,
            enabled: true,
        }
        Apperyio.__registerComponent('mobilecarousel_52', new Apperyio.ApperyMobileCarouselComponent("Heritage_north20_mobilecarousel_52", mobilecarousel_52_options));

        $("#Heritage_north20_mobilecarouselitem_53").attr("reRender", "mobilecarousel_52");

        $("#Heritage_north20_mobilecarouselitem_54").attr("reRender", "mobilecarousel_52");

        $("#Heritage_north20_mobilecarouselitem_55").attr("reRender", "mobilecarousel_52");

    };

    // screen elements handler


    function Heritage_north20_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Heritage_north20_mobileheader [name="mobilebutton_21"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('BusSelection', {
                        reverse: false
                    });

                }
            },
        }, '#Heritage_north20_mobileheader [name="mobilebutton_21"]');

        $(document).off("click", '#Heritage_north20_mobilefooter [name="mobilenavbar_22"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Heritage_north20_mobilefooter [name="mobilenavbar_22"]');
        $(document).off("click", '#Heritage_north20_mobilefooter [name="mobilenavbaritem_23"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Heritage_north20_mobilefooter [name="mobilenavbaritem_23"]');

    };

    $(document).off("pagebeforeshow", "#Heritage_north20").on("pagebeforeshow", "#Heritage_north20", function(event, ui) {
        Apperyio.CurrentScreen = "Heritage_north20";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Heritage_north20_onLoad();
};

$(document).off("pagecreate", "#Heritage_north20").on("pagecreate", "#Heritage_north20", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Heritage_north20_js();
});