/*
 * JS for Home generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c35a8c9-8dd3-4ac5-b1cb-67446d582dfb';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "SafewalkAlerts",
    "location": "SafewalkAlerts.html"
}, {
    "name": "MCampus",
    "location": "MCampus.html"
}, {
    "name": "MParkingLots",
    "location": "MParkingLots.html"
}, {
    "name": "FindClass",
    "location": "FindClass.html"
}, {
    "name": "Services",
    "location": "Services.html"
}, {
    "name": "ParkadeMapsLocations",
    "location": "ParkadeMapsLocations.html"
}, {
    "name": "Newsfeed",
    "location": "Newsfeed.html"
}, {
    "name": "MBusStop",
    "location": "MBusStop.html"
}, {
    "name": "PublicTransit",
    "location": "PublicTransit.html"
}, {
    "name": "MToujours",
    "location": "MToujours.html"
}, {
    "name": "Emergency",
    "location": "Emergency.html"
}, {
    "name": "MStudyAreas",
    "location": "MStudyAreas.html"
}, {
    "name": "BusSelection",
    "location": "BusSelection.html"
}, {
    "name": "MWashrooms",
    "location": "MWashrooms.html"
}, {
    "name": "MAED",
    "location": "MAED.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "MComp",
    "location": "MComp.html"
}, {
    "name": "BugReport",
    "location": "BugReport.html"
}, {
    "name": "MExits",
    "location": "MExits.html"
}, {
    "name": "MFE",
    "location": "MFE.html"
}, {
    "name": "ClassroomAvailability",
    "location": "ClassroomAvailability.html"
}, {
    "name": "Parkade",
    "location": "Parkade.html"
}, {
    "name": "MenuToujours",
    "location": "MenuToujours.html"
}, {
    "name": "Heritage_south20",
    "location": "Heritage_south20.html"
}, {
    "name": "Heritage_north20",
    "location": "Heritage_north20.html"
}, {
    "name": "SuccessfulSubmission",
    "location": "SuccessfulSubmission.html"
}, {
    "name": "Food",
    "location": "Food.html"
}];

function Home_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_5': 'Home_mobilebutton_5',
        'mobilebutton_8': 'Home_mobilebutton_8',
        'mobilebutton_7': 'Home_mobilebutton_7',
        'mobilebutton_6': 'Home_mobilebutton_6',
        'mobilebutton_4': 'Home_mobilebutton_4',
        'mobilebutton_3': 'Home_mobilebutton_3',
        'mobilebutton_2': 'Home_mobilebutton_2'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Home';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Home_onLoad = function() {
            Home_elementsExtraJS();

            Home_deviceEvents();
            Home_windowEvents();
            Home_elementsEvents();
        };

    // screen window events


    function Home_windowEvents() {

        $('#Home').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Home_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Home_elementsExtraJS() {
        // screen (Home) extra code

    };

    // screen elements handler


    function Home_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Home_mobilecontainer [name="mobilebutton_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('FindClass', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobilecontainer [name="mobilebutton_5"]');
        $(document).off("click", '#Home_mobilecontainer [name="mobilebutton_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Services', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobilecontainer [name="mobilebutton_8"]');
        $(document).off("click", '#Home_mobilecontainer [name="mobilebutton_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Newsfeed', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobilecontainer [name="mobilebutton_7"]');
        $(document).off("click", '#Home_mobilecontainer [name="mobilebutton_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('PublicTransit', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobilecontainer [name="mobilebutton_6"]');
        $(document).off("click", '#Home_mobilecontainer [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ParkadeMapsLocations', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobilecontainer [name="mobilebutton_4"]');
        $(document).off("click", '#Home_mobilecontainer [name="mobilebutton_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Emergency', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobilecontainer [name="mobilebutton_3"]');
        $(document).off("click", '#Home_mobilecontainer [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('BugReport', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#Home_mobilecontainer [name="mobilebutton_2"]');

    };

    $(document).off("pagebeforeshow", "#Home").on("pagebeforeshow", "#Home", function(event, ui) {
        Apperyio.CurrentScreen = "Home";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Home_onLoad();
};

$(document).off("pagecreate", "#Home").on("pagecreate", "#Home", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Home_js();
});