/*
 * JS for SafewalkAlerts generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c35a8c9-8dd3-4ac5-b1cb-67446d582dfb';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "SafewalkAlerts",
    "location": "SafewalkAlerts.html"
}, {
    "name": "MCampus",
    "location": "MCampus.html"
}, {
    "name": "MParkingLots",
    "location": "MParkingLots.html"
}, {
    "name": "FindClass",
    "location": "FindClass.html"
}, {
    "name": "Services",
    "location": "Services.html"
}, {
    "name": "ParkadeMapsLocations",
    "location": "ParkadeMapsLocations.html"
}, {
    "name": "Newsfeed",
    "location": "Newsfeed.html"
}, {
    "name": "MBusStop",
    "location": "MBusStop.html"
}, {
    "name": "PublicTransit",
    "location": "PublicTransit.html"
}, {
    "name": "MToujours",
    "location": "MToujours.html"
}, {
    "name": "Emergency",
    "location": "Emergency.html"
}, {
    "name": "MStudyAreas",
    "location": "MStudyAreas.html"
}, {
    "name": "BusSelection",
    "location": "BusSelection.html"
}, {
    "name": "MWashrooms",
    "location": "MWashrooms.html"
}, {
    "name": "MAED",
    "location": "MAED.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "MComp",
    "location": "MComp.html"
}, {
    "name": "BugReport",
    "location": "BugReport.html"
}, {
    "name": "MExits",
    "location": "MExits.html"
}, {
    "name": "MFE",
    "location": "MFE.html"
}, {
    "name": "ClassroomAvailability",
    "location": "ClassroomAvailability.html"
}, {
    "name": "Parkade",
    "location": "Parkade.html"
}, {
    "name": "MenuToujours",
    "location": "MenuToujours.html"
}, {
    "name": "Heritage_south20",
    "location": "Heritage_south20.html"
}, {
    "name": "Heritage_north20",
    "location": "Heritage_north20.html"
}, {
    "name": "SuccessfulSubmission",
    "location": "SuccessfulSubmission.html"
}, {
    "name": "Food",
    "location": "Food.html"
}];

function SafewalkAlerts_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'SafewalkAlerts_mobilebutton_2',
        'mobilegrid_7': 'SafewalkAlerts_mobilegrid_7',
        'mobilegridcell_8': 'SafewalkAlerts_mobilegridcell_8',
        'name_of_alert': 'SafewalkAlerts_name_of_alert',
        'safewalk_grid': 'SafewalkAlerts_safewalk_grid',
        'description_of_alert': 'SafewalkAlerts_description_of_alert',
        'spacer_10': 'SafewalkAlerts_spacer_10',
        'mobilebutton_9': 'SafewalkAlerts_mobilebutton_9',
        'mobilenavbar_3': 'SafewalkAlerts_mobilenavbar_3',
        'mobilenavbaritem_4': 'SafewalkAlerts_mobilenavbaritem_4'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["SafewalkAlerts_safewalk_database_onbeforesend_mapping_0"] = {
        "homeScreen": "SafewalkAlerts",
        "directions": [

        {

            "to_name": "safewalk_database",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["SafewalkAlerts_safewalk_database_onsuccess_mapping_0"] = {
        "homeScreen": "SafewalkAlerts",
        "directions": [

        {
            "from_name": "safewalk_database",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "SafewalkAlerts",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][i]",
                "target": "$['mobilegrid_7']"

            },

            {

                "source": "$['body'][i]['Alert_name']",
                "target": "$['mobilegrid_7']['name_of_alert:text']"

            },

            {

                "source": "$['body'][i]['Alert_description']",
                "target": "$['mobilegrid_7']['description_of_alert:text']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.safewalk_database = Apperyio.datasources.safewalk_database = new Apperyio.DataSource(SafeWalk_Alerts_Alerts_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["SafewalkAlerts_safewalk_database_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("SafewalkAlerts");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["SafewalkAlerts_safewalk_database_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'SafewalkAlerts';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var SafewalkAlerts_onLoad = function() {
            SafewalkAlerts_elementsExtraJS();

            try {
                safewalk_database.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            SafewalkAlerts_deviceEvents();
            SafewalkAlerts_windowEvents();
            SafewalkAlerts_elementsEvents();
        };

    // screen window events


    function SafewalkAlerts_windowEvents() {

        $('#SafewalkAlerts').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function SafewalkAlerts_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function SafewalkAlerts_elementsExtraJS() {
        // screen (SafewalkAlerts) extra code

    };

    // screen elements handler


    function SafewalkAlerts_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#SafewalkAlerts_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Emergency', {
                        reverse: false
                    });

                }
            },
        }, '#SafewalkAlerts_mobileheader [name="mobilebutton_2"]');

        $(document).off("click", '#SafewalkAlerts_mobilecontainer [name="mobilebutton_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        safewalk_database.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#SafewalkAlerts_mobilecontainer [name="mobilebutton_9"]');

        $(document).off("click", '#SafewalkAlerts_mobilefooter [name="mobilenavbaritem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#SafewalkAlerts_mobilefooter [name="mobilenavbaritem_4"]');

    };

    $(document).off("pagebeforeshow", "#SafewalkAlerts").on("pagebeforeshow", "#SafewalkAlerts", function(event, ui) {
        Apperyio.CurrentScreen = "SafewalkAlerts";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    SafewalkAlerts_onLoad();
};

$(document).off("pagecreate", "#SafewalkAlerts").on("pagecreate", "#SafewalkAlerts", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    SafewalkAlerts_js();
});