/*
 * JS for Services generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c35a8c9-8dd3-4ac5-b1cb-67446d582dfb';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "SafewalkAlerts",
    "location": "SafewalkAlerts.html"
}, {
    "name": "MCampus",
    "location": "MCampus.html"
}, {
    "name": "MParkingLots",
    "location": "MParkingLots.html"
}, {
    "name": "FindClass",
    "location": "FindClass.html"
}, {
    "name": "Services",
    "location": "Services.html"
}, {
    "name": "ParkadeMapsLocations",
    "location": "ParkadeMapsLocations.html"
}, {
    "name": "Newsfeed",
    "location": "Newsfeed.html"
}, {
    "name": "MBusStop",
    "location": "MBusStop.html"
}, {
    "name": "PublicTransit",
    "location": "PublicTransit.html"
}, {
    "name": "MToujours",
    "location": "MToujours.html"
}, {
    "name": "Emergency",
    "location": "Emergency.html"
}, {
    "name": "MStudyAreas",
    "location": "MStudyAreas.html"
}, {
    "name": "BusSelection",
    "location": "BusSelection.html"
}, {
    "name": "MWashrooms",
    "location": "MWashrooms.html"
}, {
    "name": "MAED",
    "location": "MAED.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "MComp",
    "location": "MComp.html"
}, {
    "name": "BugReport",
    "location": "BugReport.html"
}, {
    "name": "MExits",
    "location": "MExits.html"
}, {
    "name": "MFE",
    "location": "MFE.html"
}, {
    "name": "ClassroomAvailability",
    "location": "ClassroomAvailability.html"
}, {
    "name": "Parkade",
    "location": "Parkade.html"
}, {
    "name": "MenuToujours",
    "location": "MenuToujours.html"
}, {
    "name": "Heritage_south20",
    "location": "Heritage_south20.html"
}, {
    "name": "Heritage_north20",
    "location": "Heritage_north20.html"
}, {
    "name": "SuccessfulSubmission",
    "location": "SuccessfulSubmission.html"
}, {
    "name": "Food",
    "location": "Food.html"
}];

function Services_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'Services_mobilebutton_2',
        'mobilelist_21': 'Services_mobilelist_21',
        'mobilelistitem_22': 'Services_mobilelistitem_22',
        'mobilelistitembutton_23': 'Services_mobilelistitembutton_23',
        'mobilelistitem_24': 'Services_mobilelistitem_24',
        'mobilelistitembutton_25': 'Services_mobilelistitembutton_25',
        'mobilelistitem_26': 'Services_mobilelistitem_26',
        'mobilelistitembutton_27': 'Services_mobilelistitembutton_27',
        'mobilelistitem_28': 'Services_mobilelistitem_28',
        'mobilelistitembutton_29': 'Services_mobilelistitembutton_29',
        'mobilenavbar_7': 'Services_mobilenavbar_7',
        'mobilenavbaritem_8': 'Services_mobilenavbaritem_8'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Services';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Services_onLoad = function() {
            Services_elementsExtraJS();

            Services_deviceEvents();
            Services_windowEvents();
            Services_elementsEvents();
        };

    // screen window events


    function Services_windowEvents() {

        $('#Services').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Services_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Services_elementsExtraJS() {
        // screen (Services) extra code

        /* mobilelist_21 */

        listView = $("#Services_mobilelist_21");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Services_mobilelist_21 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_22 */

        /* mobilelistitem_24 */

        /* mobilelistitem_26 */

        /* mobilelistitem_28 */

    };

    // screen elements handler


    function Services_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Services_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Services_mobileheader [name="mobilebutton_2"]');

        $(document).off("click", '#Services_mobilecontainer [name="mobilelistitem_22"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Food', {
                        reverse: false
                    });

                }
            },
        }, '#Services_mobilecontainer [name="mobilelistitem_22"]');

        $(document).off("click", '#Services_mobilecontainer [name="mobilelistitem_24"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('MComp', {
                        reverse: false
                    });

                }
            },
        }, '#Services_mobilecontainer [name="mobilelistitem_24"]');

        $(document).off("click", '#Services_mobilecontainer [name="mobilelistitem_26"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('MWashrooms', {
                        reverse: false
                    });

                }
            },
        }, '#Services_mobilecontainer [name="mobilelistitem_26"]');

        $(document).off("click", '#Services_mobilecontainer [name="mobilelistitem_28"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('MStudyAreas', {
                        reverse: false
                    });

                }
            },
        }, '#Services_mobilecontainer [name="mobilelistitem_28"]');

        $(document).off("click", '#Services_mobilefooter [name="mobilenavbaritem_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Services_mobilefooter [name="mobilenavbaritem_8"]');

    };

    $(document).off("pagebeforeshow", "#Services").on("pagebeforeshow", "#Services", function(event, ui) {
        Apperyio.CurrentScreen = "Services";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Services_onLoad();
};

$(document).off("pagecreate", "#Services").on("pagecreate", "#Services", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Services_js();
});