/*
 * JS for SuccessfulSubmission generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '3c35a8c9-8dd3-4ac5-b1cb-67446d582dfb';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "SafewalkAlerts",
    "location": "SafewalkAlerts.html"
}, {
    "name": "MCampus",
    "location": "MCampus.html"
}, {
    "name": "MParkingLots",
    "location": "MParkingLots.html"
}, {
    "name": "FindClass",
    "location": "FindClass.html"
}, {
    "name": "Services",
    "location": "Services.html"
}, {
    "name": "ParkadeMapsLocations",
    "location": "ParkadeMapsLocations.html"
}, {
    "name": "Newsfeed",
    "location": "Newsfeed.html"
}, {
    "name": "MBusStop",
    "location": "MBusStop.html"
}, {
    "name": "PublicTransit",
    "location": "PublicTransit.html"
}, {
    "name": "MToujours",
    "location": "MToujours.html"
}, {
    "name": "Emergency",
    "location": "Emergency.html"
}, {
    "name": "MStudyAreas",
    "location": "MStudyAreas.html"
}, {
    "name": "BusSelection",
    "location": "BusSelection.html"
}, {
    "name": "MWashrooms",
    "location": "MWashrooms.html"
}, {
    "name": "MAED",
    "location": "MAED.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "MComp",
    "location": "MComp.html"
}, {
    "name": "BugReport",
    "location": "BugReport.html"
}, {
    "name": "MExits",
    "location": "MExits.html"
}, {
    "name": "MFE",
    "location": "MFE.html"
}, {
    "name": "ClassroomAvailability",
    "location": "ClassroomAvailability.html"
}, {
    "name": "Parkade",
    "location": "Parkade.html"
}, {
    "name": "MenuToujours",
    "location": "MenuToujours.html"
}, {
    "name": "Heritage_south20",
    "location": "Heritage_south20.html"
}, {
    "name": "Heritage_north20",
    "location": "Heritage_north20.html"
}, {
    "name": "SuccessfulSubmission",
    "location": "SuccessfulSubmission.html"
}, {
    "name": "Food",
    "location": "Food.html"
}];

function SuccessfulSubmission_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_23': 'SuccessfulSubmission_mobilebutton_23',
        'spacer_21': 'SuccessfulSubmission_spacer_21',
        'mobilelabel_19': 'SuccessfulSubmission_mobilelabel_19',
        'mobilelabel_20': 'SuccessfulSubmission_mobilelabel_20',
        'spacer_22': 'SuccessfulSubmission_spacer_22',
        'mobilebutton_18': 'SuccessfulSubmission_mobilebutton_18'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'SuccessfulSubmission';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var SuccessfulSubmission_onLoad = function() {
            SuccessfulSubmission_elementsExtraJS();

            SuccessfulSubmission_deviceEvents();
            SuccessfulSubmission_windowEvents();
            SuccessfulSubmission_elementsEvents();
        };

    // screen window events


    function SuccessfulSubmission_windowEvents() {

        $('#SuccessfulSubmission').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function SuccessfulSubmission_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function SuccessfulSubmission_elementsExtraJS() {
        // screen (SuccessfulSubmission) extra code

    };

    // screen elements handler


    function SuccessfulSubmission_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#SuccessfulSubmission_mobileheader [name="mobilebutton_23"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('BugReport', {
                        reverse: false
                    });

                }
            },
        }, '#SuccessfulSubmission_mobileheader [name="mobilebutton_23"]');

        $(document).off("click", '#SuccessfulSubmission_mobilecontainer [name="mobilebutton_18"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#SuccessfulSubmission_mobilecontainer [name="mobilebutton_18"]');

    };

    $(document).off("pagebeforeshow", "#SuccessfulSubmission").on("pagebeforeshow", "#SuccessfulSubmission", function(event, ui) {
        Apperyio.CurrentScreen = "SuccessfulSubmission";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    SuccessfulSubmission_onLoad();
};

$(document).off("pagecreate", "#SuccessfulSubmission").on("pagecreate", "#SuccessfulSubmission", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    SuccessfulSubmission_js();
});